### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by bgman111111** [TingyiChen/kernel_oppo_sm8250#1]
I my english is not good. i have realme x50 pro and want to compile latest twrp i success but decryption dont work. i ha s been insulted by captain throwback to ask him help. Make this work: https://github.com/realme-kernel-opensource/realmeX50Pro_AndroidR-kernel-source here it has missing drivers i try compile it and comment errors. if you can add all drivers in kernel oppo 8250. Man you are hacker you an do it. Why notall dveloeprs make general kernel.when compile in android aosp to ask them. what smartphone they have, and kernel source choose proper drivers... so peoples nt hestitate you. i

**Comment by TingyiChen** [comment]
I don't have devices to test, can't guarantee that unified kernel works on both devices. Also develop without real device is hard and can meet unpredictable bugs.

**Comment by bgman111111** [comment]
can you make diff . kernel and see what drivers they use and from there add them.

**Comment by bgman111111** [comment]
man it work.... i love you. please update the kernel with all drivers from realme and all kona
